name: SuperSmashBros
main: me.yurysudz.supersmashbros.Main
version: 1.0
commands:
   heal:
     description: Heal yourself or others.
   teleport:
     description: Teleport yourself.
   flipcoin:
     description: Flip a coin!
   speak:
     description: Speak to the whole server!
   ko:
     description: Kill everyone!
   motd:
     description: Shows the MOTD!
   ssb:
     description: Main super smash bros command.